"use client";

import { useEffect, useMemo, useState } from "react";
import type { HotTopic, Material, Platform } from "@/lib/studio/types";
import { PLATFORMS } from "@/lib/studio/types";
import { matchMaterials } from "@/lib/studio/match";
import type { ClassicalSearchResult } from "@/lib/studio/search";
import { CLASSICAL_SITES, classicalSearchWithExcerpts } from "@/lib/studio/search";
import { inferPlatform, nowIso, randomId } from "@/lib/studio/utils";

type LinkMetadata = {
  title?: string;
  description?: string;
};

const STORAGE_KEY = "studio_hot_topics_v1";
const STORAGE_MATERIALS_KEY = "studio_materials_v1";
const STORAGE_COMPARE_DRAFT_KEY = "studio_compare_draft_v1";
const STORAGE_CLASSICAL_SITE_IDS = "studio_classical_site_ids_v1";

function loadClassicalSiteIds(): string[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_CLASSICAL_SITE_IDS);
    if (!raw) return [];
    const data = JSON.parse(raw) as unknown;
    return Array.isArray(data) ? data.filter((x) => typeof x === "string") : [];
  } catch {
    return [];
  }
}

function saveClassicalSiteIds(ids: string[]) {
  window.localStorage.setItem(STORAGE_CLASSICAL_SITE_IDS, JSON.stringify(ids));
}

function toReaderHref(url?: string): string | undefined {
  const u = String(url ?? "").trim();
  if (!u) return undefined;
  return `/studio/reader?url=${encodeURIComponent(u)}`;
}

function isSlowHost(url?: string): boolean {
  try {
    const u = new URL(String(url ?? ""));
    return u.hostname === "zh.wikisource.org";
  } catch {
    return false;
  }
}

function loadFromStorage(): HotTopic[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const data = JSON.parse(raw) as HotTopic[];
    return Array.isArray(data) ? data : [];
  } catch {
    return [];
  }
}

function saveToStorage(items: HotTopic[]) {
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(items));
}

function loadMaterialsFromStorage(): Material[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = window.localStorage.getItem(STORAGE_MATERIALS_KEY);
    if (!raw) return [];
    const data = JSON.parse(raw) as Material[];
    return Array.isArray(data) ? data : [];
  } catch {
    return [];
  }
}

function saveMaterialsToStorage(items: Material[]) {
  window.localStorage.setItem(STORAGE_MATERIALS_KEY, JSON.stringify(items));
}

type CompareDraft = {
  topicTitle: string;
  sources: Array<{ title: string; url?: string }>;
};

function loadCompareDraft(): CompareDraft | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(STORAGE_COMPARE_DRAFT_KEY);
    if (!raw) return null;
    const data = JSON.parse(raw) as CompareDraft;
    if (!data || typeof data !== "object") return null;
    const topicTitle = typeof data.topicTitle === "string" ? data.topicTitle : "";
    const sources = Array.isArray(data.sources) ? data.sources : [];
    return { topicTitle, sources };
  } catch {
    return null;
  }
}

function saveCompareDraft(draft: CompareDraft) {
  window.localStorage.setItem(STORAGE_COMPARE_DRAFT_KEY, JSON.stringify(draft));
}

export function HotInboxClient() {
  const [items, setItems] = useState<HotTopic[]>([]);
  const [materials, setMaterials] = useState<Material[]>([]);
  const [autoGeneratedAt, setAutoGeneratedAt] = useState<string | null>(null);
  const [autoItems, setAutoItems] = useState<
    Array<{
      title: string;
      url?: string;
      platform?: Platform;
      keywords?: string[];
      collectedAt?: string;
    }>
  >([]);
  const [url, setUrl] = useState("");
  const [title, setTitle] = useState("");
  const [platform, setPlatform] = useState<Platform | "">("");
  const [summary, setSummary] = useState("");
  const [keywordsInput, setKeywordsInput] = useState("");
  const [loadingMeta, setLoadingMeta] = useState(false);
  const [metaError, setMetaError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [webLoadingByKey, setWebLoadingByKey] = useState<Record<string, boolean>>(
    {},
  );
  const [webErrorByKey, setWebErrorByKey] = useState<Record<string, string | null>>(
    {},
  );
  const [webResultsByKey, setWebResultsByKey] = useState<
    Record<string, ClassicalSearchResult[]>
  >({});
  const [classicalSiteIds, setClassicalSiteIds] = useState<string[]>(() => {
    const saved = loadClassicalSiteIds();
    if (saved.length) return saved;
    return CLASSICAL_SITES.filter((s) => s.enabledByDefault).map((s) => s.id);
  });
  const classicalHosts = useMemo(() => {
    const enabled = new Set(classicalSiteIds);
    return CLASSICAL_SITES.filter((s) => enabled.has(s.id)).flatMap((s) => s.hosts);
  }, [classicalSiteIds]);

  useEffect(() => {
    setItems(loadFromStorage());
    setMaterials(loadMaterialsFromStorage());
  }, []);

  useEffect(() => {
    async function loadAuto() {
      try {
        const resp = await fetch("/auto-hot.json", { cache: "no-store" });
        if (!resp.ok) return;
        const json = (await resp.json()) as {
          generatedAt?: string | null;
          items?: Array<{
            title: string;
            url?: string;
            platform?: Platform;
            keywords?: string[];
            collectedAt?: string;
          }>;
        };
        setAutoGeneratedAt(json.generatedAt ?? null);
        setAutoItems(Array.isArray(json.items) ? json.items : []);
      } catch {
        setAutoGeneratedAt(null);
        setAutoItems([]);
      }
    }
    loadAuto();
  }, []);

  const keywords = useMemo(() => {
    return keywordsInput
      .split(/[,\n，\s]+/g)
      .map((s) => s.trim())
      .filter(Boolean);
  }, [keywordsInput]);

  const materialMatchesByKey = useMemo(() => {
    const out: Record<string, ReturnType<typeof matchMaterials>> = {};
    const current = expanded;
    const limit = 8;
    for (const [key, isOpen] of Object.entries(current)) {
      if (!isOpen) continue;
      const raw = key.startsWith("auto:")
        ? autoItems.find((x) => `auto:${x.url ?? x.title}` === key)
        : items.find((x) => `hot:${x.id}` === key);
      if (!raw) continue;
      const hot: HotTopic =
        "id" in raw
          ? raw
          : {
              id: key,
              title: raw.title,
              url: raw.url,
              platform: raw.platform,
              summary: undefined,
              keywords: Array.isArray(raw.keywords) ? raw.keywords : [],
              createdAt: raw.collectedAt ?? nowIso(),
            };
      out[key] = matchMaterials(hot, materials, { limit });
    }
    return out;
  }, [autoItems, expanded, items, materials]);

  function toggleExpanded(key: string) {
    setExpanded((prev) => ({ ...prev, [key]: !prev[key] }));
  }

  function addSourceToCompareDraft(topicTitle: string, source: { title: string; url?: string }) {
    const draft = loadCompareDraft() ?? { topicTitle: "", sources: [] };
    const nextTopic = draft.topicTitle || topicTitle;
    const existed = new Set(
      draft.sources.map((s) => (s.url ? `u:${s.url}` : `t:${s.title}`)),
    );
    const key = source.url ? `u:${source.url}` : `t:${source.title}`;
    if (!existed.has(key)) {
      draft.sources = [...draft.sources, source];
      existed.add(key);
    }
    saveCompareDraft({ topicTitle: nextTopic, sources: draft.sources });
  }

  function saveWebResultAsMaterial(key: string, r: ClassicalSearchResult, topicTitle: string) {
    const citation = r.citation;
    const displayTitle = citation
      ? `${citation.work}${citation.locator ? ` · ${citation.locator}` : ""}`
      : r.title;
    const t = displayTitle.trim();
    if (!t) return;
    const newItem: Material = {
      id: randomId("mat"),
      title: t,
      url: citation?.canonicalUrl || r.url || undefined,
      citation: citation
        ? {
            work: citation.work,
            locator: citation.locator,
            canonicalUrl: citation.canonicalUrl,
          }
        : undefined,
      sourceType: "史料",
      credibility: "高",
      dynasties: [],
      people: [],
      events: [],
      dimensions: [],
      excerpt: r.quote?.trim() || undefined,
      notes: [
        `古籍搜索：${topicTitle}`,
        r.cacheText ? `【文字版】\n${r.cacheText.trim()}` : "",
      ]
        .filter(Boolean)
        .join("\n\n"),
      createdAt: nowIso(),
    };

    const existed = new Set(
      materials.map((x) => (x.url ? `u:${x.url}` : `t:${x.title}`)),
    );
    const k = newItem.url ? `u:${newItem.url}` : `t:${newItem.title}`;
    if (existed.has(k)) return;

    const next = [newItem, ...materials];
    setMaterials(next);
    saveMaterialsToStorage(next);
    setWebResultsByKey((prev) => {
      const list = prev[key] ?? [];
      return { ...prev, [key]: list };
    });
  }

  async function runWebSearchForHot(key: string, query: string) {
    const q = query.trim();
    if (!q) return;
    setWebLoadingByKey((prev) => ({ ...prev, [key]: true }));
    setWebErrorByKey((prev) => ({ ...prev, [key]: null }));
    try {
      const results = await classicalSearchWithExcerpts(q, {
        limit: 8,
        hosts: classicalHosts,
      });
      setWebResultsByKey((prev) => ({ ...prev, [key]: results }));
    } catch (e) {
      setWebErrorByKey((prev) => ({
        ...prev,
        [key]: e instanceof Error ? e.message : "搜索失败",
      }));
      setWebResultsByKey((prev) => ({ ...prev, [key]: [] }));
    } finally {
      setWebLoadingByKey((prev) => ({ ...prev, [key]: false }));
    }
  }

  function toggleClassicalSite(id: string) {
    setClassicalSiteIds((prev) => {
      const existed = new Set(prev);
      if (existed.has(id)) existed.delete(id);
      else existed.add(id);
      const next = [...existed];
      saveClassicalSiteIds(next);
      return next;
    });
  }

  async function fetchMetadata(targetUrl: string) {
    setLoadingMeta(true);
    setMetaError(null);
    try {
      const proxied = `https://r.jina.ai/${targetUrl}`;
      const resp = await fetch(proxied);
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
      const text = await resp.text();
      const extracted = extractFromReader(text);
      if (!title && extracted.title) setTitle(extracted.title);
      if (!summary && extracted.description) setSummary(extracted.description);
    } catch (e) {
      setMetaError(e instanceof Error ? e.message : "获取失败");
    } finally {
      setLoadingMeta(false);
    }
  }

  function onUrlBlur() {
    const p = url ? inferPlatform(url) : undefined;
    if (p && !platform) setPlatform(p);
    if (url && !title) fetchMetadata(url);
  }

  function addItem() {
    const t = title.trim();
    if (!t) return;
    const newItem: HotTopic = {
      id: randomId("hot"),
      title: t,
      url: url.trim() || undefined,
      platform: platform || (url ? inferPlatform(url) : undefined),
      summary: summary.trim() || undefined,
      keywords,
      createdAt: nowIso(),
    };
    const next = [newItem, ...items];
    setItems(next);
    saveToStorage(next);
    setUrl("");
    setTitle("");
    setPlatform("");
    setSummary("");
    setKeywordsInput("");
    setMetaError(null);
  }

  function removeItem(id: string) {
    const next = items.filter((x) => x.id !== id);
    setItems(next);
    saveToStorage(next);
  }

  function exportJson() {
    const blob = new Blob([JSON.stringify(items, null, 2)], {
      type: "application/json",
    });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "hot-topics.json";
    a.click();
    URL.revokeObjectURL(a.href);
  }

  function importAutoTopic(it: {
    title: string;
    url?: string;
    platform?: Platform;
    keywords?: string[];
  }) {
    const t = it.title.trim();
    if (!t) return;
    const newItem: HotTopic = {
      id: randomId("hot"),
      title: t,
      url: it.url?.trim() || undefined,
      platform: it.platform,
      summary: undefined,
      keywords: Array.isArray(it.keywords) ? it.keywords : [],
      createdAt: nowIso(),
    };
    const key = newItem.url ? `u:${newItem.url}` : `t:${newItem.title}`;
    const existed = new Set(
      items.map((x) => (x.url ? `u:${x.url}` : `t:${x.title}`)),
    );
    if (existed.has(key)) return;
    const next = [newItem, ...items];
    setItems(next);
    saveToStorage(next);
  }

  function importAllAuto() {
    const existed = new Set(
      items.map((x) => (x.url ? `u:${x.url}` : `t:${x.title}`)),
    );
    const toAdd: HotTopic[] = [];
    for (const it of autoItems) {
      const t = it.title.trim();
      if (!t) continue;
      const url = it.url?.trim() || undefined;
      const key = url ? `u:${url}` : `t:${t}`;
      if (existed.has(key)) continue;
      existed.add(key);
      toAdd.push({
        id: randomId("hot"),
        title: t,
        url,
        platform: it.platform,
        summary: undefined,
        keywords: Array.isArray(it.keywords) ? it.keywords : [],
        createdAt: nowIso(),
      });
    }
    if (!toAdd.length) return;
    const next = [...toAdd, ...items];
    setItems(next);
    saveToStorage(next);
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="rounded-xl border border-black/10 p-4 dark:border-white/10">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <div className="text-sm font-semibold">自动热点（每日更新）</div>
            <div className="mt-0.5 text-xs text-foreground/60">
              {autoGeneratedAt
                ? `生成时间：${new Date(autoGeneratedAt).toLocaleString()}`
                : "未检测到自动热点数据（本地可忽略，上线后由定时任务生成）"}
            </div>
          </div>
          <button
            type="button"
            onClick={importAllAuto}
            disabled={!autoItems.length}
            className="h-9 rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 disabled:opacity-50 dark:border-white/10 dark:hover:bg-white/10"
          >
            全部转入我的热点
          </button>
        </div>

        <div className="mt-3 grid gap-2">
          {autoItems.slice(0, 20).map((it) => (
            <div
              key={`${it.platform ?? "na"}:${it.url ?? it.title}`}
              className="flex flex-col gap-2 rounded-lg bg-black/5 p-3 dark:bg-white/10 sm:flex-row sm:items-start sm:justify-between"
            >
              <div className="min-w-0">
                <div className="truncate text-sm font-medium">{it.title}</div>
                <div className="mt-0.5 flex flex-wrap gap-x-3 gap-y-1 text-xs text-foreground/60">
                  {it.platform ? (
                    <span>
                      平台：
                      {PLATFORMS.find((p) => p.value === it.platform)?.label ??
                        it.platform}
                    </span>
                  ) : null}
                  {it.collectedAt ? (
                    <span>{new Date(it.collectedAt).toLocaleString()}</span>
                  ) : null}
                  {it.url ? (
                    <a
                      href={it.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="truncate hover:text-foreground"
                    >
                      链接
                    </a>
                  ) : null}
                </div>
                {it.keywords?.length ? (
                  <div className="mt-2 flex flex-wrap gap-2">
                    {it.keywords.slice(0, 6).map((k) => (
                      <span
                        key={`${it.title}:${k}`}
                        className="rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 dark:border-white/10"
                      >
                        {k}
                      </span>
                    ))}
                  </div>
                ) : null}

                <div className="mt-3 flex flex-wrap gap-2">
                  <button
                    type="button"
                    onClick={() => toggleExpanded(`auto:${it.url ?? it.title}`)}
                    className="h-8 rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
                  >
                    推荐材料
                  </button>
                  <a
                    href="/studio/compare"
                    className="h-8 rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
                  >
                    去对照卡
                  </a>
                </div>

                {expanded[`auto:${it.url ?? it.title}`] ? (
                  <div className="mt-3 grid gap-2">
                    {materialMatchesByKey[`auto:${it.url ?? it.title}`]?.length ? (
                      materialMatchesByKey[`auto:${it.url ?? it.title}`].map((m) => (
                        <div
                          key={m.material.id}
                          className="rounded-lg border border-black/10 bg-transparent p-3 text-sm dark:border-white/10"
                        >
                          <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                            <div className="min-w-0">
                              <div className="truncate font-medium">
                                {m.material.title}
                              </div>
                              <div className="mt-0.5 flex flex-wrap gap-x-3 gap-y-1 text-xs text-foreground/60">
                                <span>
                                  {m.material.sourceType} / {m.material.credibility}
                                </span>
                                <span>相关度：{m.score}</span>
                                {m.material.url ? (
                                  <a
                                    href={m.material.url}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="truncate hover:text-foreground"
                                  >
                                    打开
                                  </a>
                                ) : null}
                              </div>
                              {(m.reason.tokens.length ||
                                m.reason.dimensions.length ||
                                m.reason.dynasties.length) ? (
                                <div className="mt-2 flex flex-wrap gap-2">
                                  {m.reason.tokens.slice(0, 6).map((t) => (
                                    <span
                                      key={`${m.material.id}:${t}`}
                                      className="rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 dark:border-white/10"
                                    >
                                      {t}
                                    </span>
                                  ))}
                                  {m.reason.dimensions.map((d) => (
                                    <span
                                      key={`${m.material.id}:${d}`}
                                      className="rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 dark:border-white/10"
                                    >
                                      {d}
                                    </span>
                                  ))}
                                  {m.reason.dynasties.map((d) => (
                                    <span
                                      key={`${m.material.id}:${d}`}
                                      className="rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 dark:border-white/10"
                                    >
                                      {d}
                                    </span>
                                  ))}
                                </div>
                              ) : null}
                            </div>
                            <button
                              type="button"
                              onClick={() =>
                                addSourceToCompareDraft(it.title, {
                                  title: m.material.title,
                                  url: toReaderHref(m.material.url) ?? m.material.url,
                                })
                              }
                              className="h-9 shrink-0 self-start rounded-lg bg-foreground px-3 text-xs font-medium text-background hover:bg-foreground/90"
                            >
                              加入对照卡来源
                            </button>
                          </div>
                        </div>
                      ))
                    ) : (
                      <div className="text-xs text-foreground/60">
                        暂无推荐。先去材料库补充一些资料会更准。
                      </div>
                    )}

                    <div className="mt-2 rounded-lg border border-black/10 p-3 text-sm dark:border-white/10">
                      <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                        <div>
                          <div className="text-xs font-medium">在线搜索补充材料</div>
                          {webErrorByKey[`auto:${it.url ?? it.title}`] ? (
                            <div className="mt-1 text-xs text-foreground/60">
                              搜索失败：
                              {webErrorByKey[`auto:${it.url ?? it.title}`]}
                            </div>
                          ) : null}
                          <div className="mt-2 flex flex-wrap gap-2">
                            {CLASSICAL_SITES.map((s) => {
                              const on = classicalSiteIds.includes(s.id);
                              return (
                                <button
                                  key={s.id}
                                  type="button"
                                  onClick={() => toggleClassicalSite(s.id)}
                                  className={
                                    on
                                      ? "rounded-full bg-foreground px-2 py-0.5 text-xs text-background"
                                      : "rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
                                  }
                                >
                                  {s.label}
                                </button>
                              );
                            })}
                          </div>
                        </div>
                        <button
                          type="button"
                          onClick={() =>
                            runWebSearchForHot(
                              `auto:${it.url ?? it.title}`,
                              it.title,
                            )
                          }
                          disabled={webLoadingByKey[`auto:${it.url ?? it.title}`]}
                          className="h-9 shrink-0 self-start rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 disabled:opacity-50 dark:border-white/10 dark:hover:bg-white/10"
                        >
                          {webLoadingByKey[`auto:${it.url ?? it.title}`]
                            ? "搜索中"
                            : "用标题搜古籍"}
                        </button>
                      </div>

                      {webResultsByKey[`auto:${it.url ?? it.title}`]?.length ? (
                        <div className="mt-3 grid gap-2">
                          {webResultsByKey[`auto:${it.url ?? it.title}`].map((r) => (
                            <div
                              key={r.citation?.canonicalUrl ?? r.url ?? r.title}
                              className="rounded-lg bg-black/5 p-3 dark:bg-white/10"
                            >
                              <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                                <div className="min-w-0">
                                  <div className="truncate text-sm font-medium">
                                    {r.citation
                                      ? `${r.citation.work}${r.citation.locator ? ` · ${r.citation.locator}` : ""}`
                                      : r.title}
                                  </div>
                                  <div className="mt-0.5 flex flex-wrap gap-x-3 gap-y-1 text-xs text-foreground/60">
                                    {r.citation?.canonicalUrl || r.url ? (
                                      <>
                                        <a
                                          href={toReaderHref(r.citation?.canonicalUrl ?? r.url)}
                                          target="_blank"
                                          rel="noopener noreferrer"
                                          className="truncate hover:text-foreground"
                                        >
                                          阅读版
                                        </a>
                                        {!isSlowHost(r.citation?.canonicalUrl ?? r.url) ? (
                                          <a
                                            href={r.citation?.canonicalUrl ?? r.url}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="truncate hover:text-foreground"
                                          >
                                            原站
                                          </a>
                                        ) : null}
                                      </>
                                    ) : null}
                                  </div>
                                  {r.quote ? (
                                    <div className="mt-2 line-clamp-3 text-xs text-foreground/60">
                                      {r.quote}
                                    </div>
                                  ) : r.note ? (
                                    <div className="mt-2 text-xs text-foreground/60">
                                      {r.note}
                                    </div>
                                  ) : null}
                                </div>
                                <div className="flex gap-2">
                                  <button
                                    type="button"
                                    onClick={() =>
                                      saveWebResultAsMaterial(
                                        `auto:${it.url ?? it.title}`,
                                        r,
                                        it.title,
                                      )
                                    }
                                    className="h-9 shrink-0 self-start rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
                                  >
                                    保存为史料
                                  </button>
                                  <button
                                    type="button"
                                    onClick={() =>
                                      addSourceToCompareDraft(it.title, {
                                        title: r.citation
                                          ? `${r.citation.work}${r.citation.locator ? ` · ${r.citation.locator}` : ""}`
                                          : r.title,
                                        url: toReaderHref(r.citation?.canonicalUrl ?? r.url),
                                      })
                                    }
                                    className="h-9 shrink-0 self-start rounded-lg bg-foreground px-3 text-xs font-medium text-background hover:bg-foreground/90"
                                  >
                                    加入对照卡来源
                                  </button>
                                </div>
                              </div>
                            </div>
                          ))}
                        </div>
                      ) : null}
                    </div>
                  </div>
                ) : null}
              </div>
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => importAutoTopic(it)}
                  className="h-9 shrink-0 self-start rounded-lg bg-foreground px-3 text-xs font-medium text-background hover:bg-foreground/90"
                >
                  转入
                </button>
              </div>
            </div>
          ))}
          {!autoItems.length ? (
            <div className="text-sm text-foreground/60">
              暂无数据。你仍然可以使用下面的“手动入库”。
            </div>
          ) : null}
        </div>
      </div>

      <div className="rounded-xl border border-black/10 p-4 dark:border-white/10">
        <div className="grid gap-3 sm:grid-cols-2">
          <div className="flex flex-col gap-1 sm:col-span-2">
            <label className="text-sm font-medium" htmlFor="url">
              链接（可选）
            </label>
            <div className="flex gap-2">
              <input
                id="url"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                onBlur={onUrlBlur}
                placeholder="粘贴微博/抖音/微信/小红书/B站链接"
                className="h-11 flex-1 rounded-lg border border-black/10 bg-transparent px-3 text-sm outline-none focus:border-black/30 dark:border-white/10 dark:focus:border-white/30"
              />
              <button
                type="button"
                onClick={() => url && fetchMetadata(url)}
                disabled={!url || loadingMeta}
                className="h-11 rounded-lg border border-black/10 px-4 text-sm font-medium hover:bg-black/5 disabled:opacity-50 dark:border-white/10 dark:hover:bg-white/10"
              >
                {loadingMeta ? "抓取中" : "抓取标题"}
              </button>
            </div>
            {metaError ? (
              <div className="text-xs text-foreground/60">
                抓取失败：{metaError}
              </div>
            ) : null}
          </div>

          <div className="flex flex-col gap-1 sm:col-span-2">
            <label className="text-sm font-medium" htmlFor="title">
              标题
            </label>
            <input
              id="title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="一句话描述这个热点"
              className="h-11 rounded-lg border border-black/10 bg-transparent px-3 text-sm outline-none focus:border-black/30 dark:border-white/10 dark:focus:border-white/30"
            />
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium" htmlFor="platform">
              平台
            </label>
            <select
              id="platform"
              value={platform}
              onChange={(e) => setPlatform(e.target.value as Platform)}
              className="h-11 rounded-lg border border-black/10 bg-transparent px-3 text-sm outline-none focus:border-black/30 dark:border-white/10 dark:focus:border-white/30"
            >
              <option value="">自动识别/不填</option>
              {PLATFORMS.map((p) => (
                <option key={p.value} value={p.value}>
                  {p.label}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium" htmlFor="keywords">
              关键词
            </label>
            <input
              id="keywords"
              value={keywordsInput}
              onChange={(e) => setKeywordsInput(e.target.value)}
              placeholder="用空格/逗号分隔"
              className="h-11 rounded-lg border border-black/10 bg-transparent px-3 text-sm outline-none focus:border-black/30 dark:border-white/10 dark:focus:border-white/30"
            />
          </div>

          <div className="flex flex-col gap-1 sm:col-span-2">
            <label className="text-sm font-medium" htmlFor="summary">
              摘要（可选）
            </label>
            <textarea
              id="summary"
              value={summary}
              onChange={(e) => setSummary(e.target.value)}
              placeholder="可写你对这个热点的角度/疑问点"
              className="min-h-24 rounded-lg border border-black/10 bg-transparent px-3 py-2 text-sm outline-none focus:border-black/30 dark:border-white/10 dark:focus:border-white/30"
            />
          </div>
        </div>

        <div className="mt-4 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <div className="text-xs text-foreground/60">
            本地存储版本：先用于快速入库；后续可接入 Notion 做云端同步。
          </div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={exportJson}
              className="h-10 rounded-lg border border-black/10 px-4 text-sm font-medium hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
            >
              导出 JSON
            </button>
            <button
              type="button"
              onClick={addItem}
              className="h-10 rounded-lg bg-foreground px-4 text-sm font-medium text-background hover:bg-foreground/90"
            >
              入库
            </button>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-between">
        <div className="text-sm text-foreground/70">共 {items.length} 条</div>
      </div>

      <div className="grid gap-3">
        {items.map((it) => (
          <div
            key={it.id}
            className="rounded-xl border border-black/10 p-4 dark:border-white/10"
          >
            <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
              <div className="min-w-0">
                <div className="truncate text-sm font-semibold">{it.title}</div>
                <div className="mt-0.5 flex flex-wrap gap-x-3 gap-y-1 text-xs text-foreground/60">
                  <span>{new Date(it.createdAt).toLocaleString()}</span>
                  {it.platform ? (
                    <span>
                      平台：
                      {PLATFORMS.find((p) => p.value === it.platform)?.label ??
                        it.platform}
                    </span>
                  ) : null}
                  {it.url ? (
                    <a
                      href={it.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="truncate hover:text-foreground"
                    >
                      {it.url}
                    </a>
                  ) : null}
                </div>
              </div>
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={() => toggleExpanded(`hot:${it.id}`)}
                  className="h-9 self-start rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
                >
                  推荐材料
                </button>
                <a
                  href="/studio/compare"
                  className="h-9 self-start rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
                >
                  去对照卡
                </a>
                <button
                  type="button"
                  onClick={() => removeItem(it.id)}
                  className="h-9 self-start rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
                >
                  删除
                </button>
              </div>
            </div>
            {it.summary ? (
              <div className="mt-2 text-sm text-foreground/70">{it.summary}</div>
            ) : null}
            {it.keywords.length ? (
              <div className="mt-3 flex flex-wrap gap-2">
                {it.keywords.map((k) => (
                  <span
                    key={k}
                    className="rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 dark:border-white/10"
                  >
                    {k}
                  </span>
                ))}
              </div>
            ) : null}

            {expanded[`hot:${it.id}`] ? (
              <div className="mt-3 grid gap-2">
                {materialMatchesByKey[`hot:${it.id}`]?.length ? (
                  materialMatchesByKey[`hot:${it.id}`].map((m) => (
                    <div
                      key={m.material.id}
                      className="rounded-lg border border-black/10 bg-transparent p-3 text-sm dark:border-white/10"
                    >
                      <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                        <div className="min-w-0">
                          <div className="truncate font-medium">{m.material.title}</div>
                          <div className="mt-0.5 flex flex-wrap gap-x-3 gap-y-1 text-xs text-foreground/60">
                            <span>
                              {m.material.sourceType} / {m.material.credibility}
                            </span>
                            <span>相关度：{m.score}</span>
                            {m.material.url ? (
                              <a
                                href={toReaderHref(m.material.url) ?? m.material.url}
                                target="_blank"
                                rel="noopener noreferrer"
                                className="truncate hover:text-foreground"
                              >
                                阅读
                              </a>
                            ) : null}
                          </div>
                          {(m.reason.tokens.length ||
                            m.reason.dimensions.length ||
                            m.reason.dynasties.length) ? (
                            <div className="mt-2 flex flex-wrap gap-2">
                              {m.reason.tokens.slice(0, 6).map((t) => (
                                <span
                                  key={`${m.material.id}:${t}`}
                                  className="rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 dark:border-white/10"
                                >
                                  {t}
                                </span>
                              ))}
                              {m.reason.dimensions.map((d) => (
                                <span
                                  key={`${m.material.id}:${d}`}
                                  className="rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 dark:border-white/10"
                                >
                                  {d}
                                </span>
                              ))}
                              {m.reason.dynasties.map((d) => (
                                <span
                                  key={`${m.material.id}:${d}`}
                                  className="rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 dark:border-white/10"
                                >
                                  {d}
                                </span>
                              ))}
                            </div>
                          ) : null}
                        </div>
                        <button
                          type="button"
                          onClick={() =>
                            addSourceToCompareDraft(it.title, {
                              title: m.material.title,
                              url: toReaderHref(m.material.url) ?? m.material.url,
                            })
                          }
                          className="h-9 shrink-0 self-start rounded-lg bg-foreground px-3 text-xs font-medium text-background hover:bg-foreground/90"
                        >
                          加入对照卡来源
                        </button>
                      </div>
                    </div>
                  ))
                ) : (
                  <div className="text-xs text-foreground/60">
                    暂无推荐。先去材料库补充一些资料会更准。
                  </div>
                )}

                <div className="mt-2 rounded-lg border border-black/10 p-3 text-sm dark:border-white/10">
                  <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                    <div>
                      <div className="text-xs font-medium">在线搜索补充材料</div>
                      {webErrorByKey[`hot:${it.id}`] ? (
                        <div className="mt-1 text-xs text-foreground/60">
                          搜索失败：{webErrorByKey[`hot:${it.id}`]}
                        </div>
                      ) : null}
                      <div className="mt-2 flex flex-wrap gap-2">
                        {CLASSICAL_SITES.map((s) => {
                          const on = classicalSiteIds.includes(s.id);
                          return (
                            <button
                              key={s.id}
                              type="button"
                              onClick={() => toggleClassicalSite(s.id)}
                              className={
                                on
                                  ? "rounded-full bg-foreground px-2 py-0.5 text-xs text-background"
                                  : "rounded-full border border-black/10 px-2 py-0.5 text-xs text-foreground/70 hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
                              }
                            >
                              {s.label}
                            </button>
                          );
                        })}
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => runWebSearchForHot(`hot:${it.id}`, it.title)}
                      disabled={webLoadingByKey[`hot:${it.id}`]}
                      className="h-9 shrink-0 self-start rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 disabled:opacity-50 dark:border-white/10 dark:hover:bg-white/10"
                    >
                      {webLoadingByKey[`hot:${it.id}`] ? "搜索中" : "用标题搜古籍"}
                    </button>
                  </div>

                  {webResultsByKey[`hot:${it.id}`]?.length ? (
                    <div className="mt-3 grid gap-2">
                      {webResultsByKey[`hot:${it.id}`].map((r) => (
                        <div
                          key={r.citation?.canonicalUrl ?? r.url ?? r.title}
                          className="rounded-lg bg-black/5 p-3 dark:bg-white/10"
                        >
                          <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                            <div className="min-w-0">
                              <div className="truncate text-sm font-medium">
                                {r.citation
                                  ? `${r.citation.work}${r.citation.locator ? ` · ${r.citation.locator}` : ""}`
                                  : r.title}
                              </div>
                              <div className="mt-0.5 flex flex-wrap gap-x-3 gap-y-1 text-xs text-foreground/60">
                                {r.citation?.canonicalUrl || r.url ? (
                                  <>
                                    <a
                                      href={toReaderHref(r.citation?.canonicalUrl ?? r.url)}
                                      target="_blank"
                                      rel="noopener noreferrer"
                                      className="truncate hover:text-foreground"
                                    >
                                      阅读版
                                    </a>
                                    {!isSlowHost(r.citation?.canonicalUrl ?? r.url) ? (
                                      <a
                                        href={r.citation?.canonicalUrl ?? r.url}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="truncate hover:text-foreground"
                                      >
                                        原站
                                      </a>
                                    ) : null}
                                  </>
                                ) : null}
                              </div>
                              {r.quote ? (
                                <div className="mt-2 line-clamp-3 text-xs text-foreground/60">
                                  {r.quote}
                                </div>
                              ) : r.note ? (
                                <div className="mt-2 text-xs text-foreground/60">
                                  {r.note}
                                </div>
                              ) : null}
                            </div>
                            <div className="flex gap-2">
                              <button
                                type="button"
                                onClick={() =>
                                  saveWebResultAsMaterial(`hot:${it.id}`, r, it.title)
                                }
                                className="h-9 shrink-0 self-start rounded-lg border border-black/10 px-3 text-xs font-medium hover:bg-black/5 dark:border-white/10 dark:hover:bg-white/10"
                              >
                                保存为史料
                              </button>
                              <button
                                type="button"
                                onClick={() =>
                                  addSourceToCompareDraft(it.title, {
                                    title: r.citation
                                      ? `${r.citation.work}${r.citation.locator ? ` · ${r.citation.locator}` : ""}`
                                      : r.title,
                                    url: toReaderHref(r.citation?.canonicalUrl ?? r.url),
                                  })
                                }
                                className="h-9 shrink-0 self-start rounded-lg bg-foreground px-3 text-xs font-medium text-background hover:bg-foreground/90"
                              >
                                加入对照卡来源
                              </button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : null}
                </div>
              </div>
            ) : null}
          </div>
        ))}
      </div>
    </div>
  );
}

function extractFromReader(text: string): LinkMetadata {
  const title =
    text.match(/^Title:\s*(.+)$/m)?.[1]?.trim() ??
    text.match(/^#\s+(.+)$/m)?.[1]?.trim() ??
    undefined;

  const description =
    text.match(/^Description:\s*(.+)$/m)?.[1]?.trim() ??
    text.match(/^Excerpt:\s*(.+)$/m)?.[1]?.trim() ??
    undefined;

  return { title, description };
}

